### ISSUE TITLE
Google Auth Bug

### ISSUE THREAD

**Issue by slavakurilyak** [13point5/open-artifacts-renderer#1]
While trying to create an account for [openartifacts.vercel.app](https://openartifacts.vercel.app/), Google auth takes me to:

> http://localhost:3000/?code=f7b5610b-6504-4002-ade5-d752a744aa7e

<img width="737" alt="Screen Shot 2024-07-23 at 9 38 39 PM" src="https://github.com/user-attachments/assets/c817d03e-9f70-4c44-9c8d-ec347b750024">

**Comment by 13point5** [comment]
Hey sorry for the bug, just fixed it! Please let me know if it still persists!
